#!/usr/bin/env bash
# Authors: Gabriel Theuws
# Translate : Gabriel Theuws
# Contact: thiagos.dasilva@gmail.com
# Contact: gaby.theuws@gmail.com
# URL origin: https://github.com/thiggy01/ubuntu-20.04-change-gdm-background
# URL translation: https://github.com/Amiralgaby/ubuntu-change-gdm-background
# =================================================================== #

usage () {
    cat << EOF
Utilisation avec privilège administrateur:
  $0 [OPTIONS]

OPTIONS :
  --cache-filigrane             -   Cache le logo Ubuntu sur l'écran de connexion
                                    et par la même occasion celui du boot
  --restore                     -   Restaure l'ancien thème
EOF
}

[ "$1" == "-h" ] && usage && exit 0

# Check if script is run by root.
if [ "$(id -u)" -ne 0 ] ; then
    echo 'Ce script doit être exécuté en tant que root ou avec la commande sudo.' >&2
    usage
    exit 1
fi

[ -f /etc/os-release ] && . /etc/os-release

# Check what linux distro is being used.
if ! [[ "$VERSION_CODENAME" =~ (focal|groovy) ]]; then
    echo "Désolé, ce script ne fonctionne qu'avec des distros focal ou groovy." >&2
    exit 1
fi

# Check if glib 2.0 development libraries are installed.
command -v glib-compile-resources >/dev/null 2>&1 || { 
    echo "La commande glib-compile-resources n'a pas été trouvée" >&2
    echo "Ce script ne peut pas fonctionner sans les bibliothèques nécessaires" >&2
    exit 1
}

# Assign the default gdm theme file path.
if [ "$NAME" == 'Ubuntu' ]; then
    gdm3Resource=/usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource
elif [ "$NAME" == 'Pop' ]; then
    gdm3Resource=/usr/share/gnome-shell/theme/Pop/gnome-shell-theme.gresource
fi

# Create a backup file of the original theme if there isn't one.
[ ! -f "$gdm3Resource"~ ] && cp "$gdm3Resource" "$gdm3Resource~"

# Restore backup function.
restore () {
    if mv "$gdm3Resource~" "$gdm3Resource"; then
        chmod 644 "$gdm3Resource"
        echo 'Le fond GDM a été restauré avec succès.'
        exit 0
    fi
}

# Restore the original gdm3 theme.
[ "$1" == "--restore" ] && restore

#Define main variables.
gdm3xml=${gdm3Resource##*/}.xml
workDir="/tmp/gdm3-theme"

# Create directories from resource list.
CreateDirs() {
    for resource in $(gresource list "$gdm3Resource~"); do
        resource="${resource#\/org\/gnome\/shell\/}"
        if [ ! -d "$workDir"/"${resource%/*}" ]; then
            mkdir -p "$workDir"/"${resource%/*}"
        fi
    done
}

# Extract resources from binary file.
ExtractRes() {
    for resource in $(gresource list "$gdm3Resource~"); do
        gresource extract "$gdm3Resource~" "$resource" > \
            "$workDir"/"${resource#\/org\/gnome\/shell\/}"
    done
}

# Compile resources into a gresource binary file.
CompileMoveRes() {

    glib-compile-resources --sourcedir=$workDir/theme/ $workDir/theme/"$gdm3xml"

    # Move the generated binary file to the gnome-shell folder.

    if mv $workDir/theme/gnome-shell-theme.gresource $gdm3Resource; then
        # Solve a permission change issue (thanks to @huepf from github).
        chmod 644 "$gdm3Resource"
        echo "L'arrière-plan de l'écran de connexion a changé avec succès."
    else
        # If something went wrong, restore backup file.
        echo "quelque chose s'est mal passé." >&2
        restore
        echo "Aucun changement n'a été appliqué" >&2
    fi

    # Remove temporary directories and files.
    rm -r "$workDir"
    exit 0
}

runApp() {

# Define image variables.
imgFile="${1##*/}"

# Call procedures to create directories and extract resources to them.
ExtractRes

# Change gdm background to the image you submited.
oldBg="#lockDialogGroup \{.*?\}"
newBg="#lockDialogGroup {
    background: url('resource:\/\/\/org\/gnome\/shell\/theme\/$imgFile');
    background-size: cover; }"
perl -i -0777 -pe "s/$oldBg/$newBg/s" "$workDir"/theme/gdm3.css

filesXML=""
for file in $(gresource list "$gdm3Resource~"); do
	filesXML="$filesXML
		<file>${file#\/org\/gnome/shell\/theme\/}</file>"
done

filesXML="$filesXML
		<file>$imgFile</file>"

pathXML=""$workDir"/theme/"$gdm3xml""
# Generate gresource xml file.
cat <<EOF > "$pathXML"
<?xml version="1.0" encoding="UTF-8"?>
<gresources>
    <gresource prefix="/org/gnome/shell/theme">
    	$filesXML
    </gresource>
</gresources>
EOF

# Compile and move gresource.
CompileMoveRes
}

CreateDirs

PATH_TO_IMG="$workDir"/theme/image

if nc -zw1 picsum.photos 443
then 
    echo "Connexion active" 
    wget --no-verbose https://picsum.photos/1600/900 -6 -O "$PATH_TO_IMG"
else
    echo "Problème pour se connecter" >&2
    exit 1
fi

[ -f "$PATH_TO_IMG" ] && runApp "$PATH_TO_IMG" || echo "Le fichier \"$PATH_TO_IMG\" n'a pas été trouvé"
